### ISSUE TITLE
new formats ui loses form state after collapsing accordion

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#1130]
1. Log in to https://unstable.aws.bmlt.app/.
2. Go to Formats.
3. Click any format, e.g. "Agnostic". The modal will open.
4. Observe the English accordion opens, and the form fields show the correct values.
5. Collapse the English accordion, and then reopen it.
6. Observe the form fields are now empty.

**Comment by pjaudiomv** [comment]
This prob has to do with the Accordian component which has caused other issues with testing. Could be those both are resolved by implementing our own accordion that just hides with css

**Comment by alanb2718** [comment]
It looks like this is a known problem: https://github.com/themesberg/flowbite-svelte/issues/1070

Unfortunately it doesn't look like this is going to get fixed in the near future.  So yes, we should either just show/hide with css, or not use Accordion.  I'd be willing to just not use it -- annoying but not catastrophic.  The two places it's currently used are the Format modal, and the list of service bodies on the Account tab.  For both of these, we could just show all of the information and not support collapsing it.
