### ISSUE TITLE
problem with venue type radio buttons in Danish, German, and Russian

### ISSUE THREAD

**Issue by alanborning** [bmlt-enabled/bmlt-root-server#379]
Something isn't working quite right with the new venue type radio buttons in some non-English languages.

In Danish and German,  the editor doesn't think anything changed if you just pick a different radio button. If you make an additional edit, though, the radio button is remembered.

In Russian, the original choice of venue type doesn't show up at all with the buttons.

**Comment by radius314** [comment]
This is a weird one.  Looking at it.

**Comment by radius314** [comment]
Ok the Russian choice doesn't show because there are no format codes populated for Russian.

![image](https://user-images.githubusercontent.com/1850811/106688730-a4da3700-659c-11eb-93a3-6a7aec467fd2.png)

![image](https://user-images.githubusercontent.com/1850811/106688780-c2a79c00-659c-11eb-9c12-0336a5723d98.png)

We could probably fall back to English.  Thoughts?

**Comment by radius314** [comment]
I would gather that Danish + German are the same issue.
