### ISSUE TITLE
Semantic Workshop - Simple HTML (Table) missing results

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt-root-server#425]
When you use the semantic workshop and choose either "**Simple HTML (Table)**" or "**SImple HTML (block elements)**" from the "_The Returned Data Will Be:_" drop down, the results are incomplete. It appears that any meeting which does not have data in the location_text, location_info, or location_street fields is excluded. 

You can test by using this query. This searches the Connecticut root server for all meeting that are either VM or HY. Almost all of the pure VM meetings are not displayed in the results because they have no location info (there are one or two in the list which are probably mistakes in our data). 
[https://ctna.org/main_server/client_interface/simple/?switcher=GetSearchResults&formats[]=57&formats[]=59&formats_comparison_operator=OR](https://ctna.org/main_server/client_interface/simple/?switcher=GetSearchResults&formats[]=57&formats[]=59&formats_comparison_operator=OR)

For comparison, run the same query with the returned data being a CSV file. You will see the full expected results.  
[https://ctna.org/main_server/client_interface/csv/?switcher=GetSearchResults&formats[]=57&formats[]=59&formats_comparison_operator=OR](https://ctna.org/main_server/client_interface/csv/?switcher=GetSearchResults&formats[]=57&formats[]=59&formats_comparison_operator=OR)

**Comment by ChrisMarshallNY** [comment]
That’s a good bug report.

I don’t know if Crouton uses the simple response anymore, but when Jack first wrote it, he used that format. One of the reasons the old Tabbed UI took so long to load, was because he would make seven separate simple searches. I know it got a lot faster, after Danny took it over.

I’d posit that we may want to discus whether or not we still want to support this format at all. With CroutonJS, the need for it has diminished. I used to use it in my Quick Search, but the classic plugin has been deprecated.

**Comment by pjaudiomv** [comment]
with the exception of naws exports (csv) only json responses will be in 3.0
